basePath: /
definitions:
  entities.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  entities.Order:
    properties:
      amount:
        type: number
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      user_id:
        type: integer
    type: object
  entities.User:
    properties:
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API para autenticação de usuários em GOlang
  title: Login API
  version: "1.0"
paths:
  /createOrder:
    post:
      consumes:
      - application/json
      parameters:
      - description: Order
        in: body
        name: order
        required: true
        schema:
          $ref: '#/definitions/entities.Order'
      responses: {}
      security:
      - ApiKeyAuth: []
  /createUser:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      responses: {}
      security:
      - ApiKeyAuth: []
  /deleteOrder/{id}:
    delete:
      responses: {}
      security:
      - ApiKeyAuth: []
  /getOrders:
    get:
      responses: {}
      security:
      - ApiKeyAuth: []
  /getUsers:
    get:
      responses: {}
      security:
      - ApiKeyAuth: []
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login Request
        in: body
        name: loginRequest
        required: true
        schema:
          $ref: '#/definitions/entities.LoginRequest'
      responses: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
